### ISSUE TITLE
Debian support?

### ISSUE THREAD

**Issue by LarsNorgaard** [miquiloni/miquiloni#1]
Will we see any debian as a host being supported?

Keep up the good work :)

**Comment by HugoMaza** [comment]
Hi my friend,

Yes, we have plans to support **Open SuSE, Oracle Linux and Debian** too.
There are a lot of pending tasks to do and little free time.   :(
Please be patient and we'll have good progress as soon as posible.

Thanks to take a time for see our project and write.

Best Regards
Hugo Maza
